version: "3.3"

services:
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: finalk
      MYSQL_DATABASE: finalfantastik
    ports:
    - 3306:3306
  phpmya:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
    - 8899:80